### ISSUE TITLE
error when trying to browserify

### ISSUE THREAD

**Issue by pbaille** [gre/multi-slider#3]
I'm trying to browserify index.js and got this error 

$ browserify src/index.js > bundle.js

Error: Cannot find module 'react/lib/invariant' from '/Users/user1/Documents/Code/multi-slider/node_modules/uncontrollable/lib'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

Am I missing something?

**Comment by gre** [comment]
looks like it's a bug in `uncontrollable`, feel free to fork multi-slider, update `uncontrollable`, test it and submit a PR :)

**Comment by pbaille** [comment]
thanks for the answer I will look at this as soon as possible

**Comment by mic159** [comment]
Same error for me when trying to use this with React 15 + webpack.

**Comment by gre** [comment]
I've released a 3.0.0 that should work with latest libs

**Comment by mic159** [comment]
Thanks! It works!
